name: CI

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package with dependencies
        run: |
          make develop

      - name: Run tests
        run: |
          make tests

      - name: Generate coverage report
        run: |
          coverage report
